#Lösung für aufgabe 3 a)
w = rnorm(1000,sd=5)
w = ts(w)
x = w+0.2*lag(w)
plot(x,main="Process x")
v = rnorm(1000)
v = ts(v)
y = v+5*lag(v)
plot(y,main="Process y")
#Lösung für aufgabe 3 b)
acf(x)
acf(y)
